### ISSUE TITLE
JHipster Generation Module Step Crash

### ISSUE THREAD

**Issue by ruddell** [bastienmichaux/generator-jhipster-db-helper#1]
The initial v0.0.1 package.json published to NPM has the author entry as a list instead of an object (this is fixed in your current package.json).  This crashes all released versions of JHipster on the module step during generation.  It was an oversight on my part, I expected all author fields to be objects as per [the spec](https://docs.npmjs.com/files/package.json).  

Would you guys mind publishing v0.0.2 of your module with the updated package.json?  The issue is tracked https://github.com/jhipster/generator-jhipster/issues/5563 and already has a PR to fix it in future versions, but all versions <= v4.2.0 will still crash until this is changed.

**Comment by AdrienHorgnies** [comment]
Will do that asap.

**Comment by bastienmichaux** [comment]
I had no idea this could happen. To be double-sure I published the corrected version on NPM too. My bad for not following the spec. Thank you @ruddell for pointing this out to us.

**Comment by ruddell** [comment]
Thanks for the fix!  I like the idea of this module, it's an often requested feature

**Comment by pascalgrimaud** [comment]
1. Not your fault at all. Author is not mandatory when you publish to npm, and in the generator-jhipster-module, it's not mandatory either. Anyway, thanks for preventing the bug by publishing a new one :)

2. At DevoxxFR, after demo, several people asked me : is it possible to generate a JHipster project from an existing database ? As Ruddell, I loved this idea!

@AdrienHorgnies @bastienmichaux : don't hesitate to make a sexy tweet and mention `@java_hipster`, it can be retweeted, so some people can discover this module, have a look, test your module and maybe contribute to it
