### ISSUE TITLE
Do Unit Tests

### ISSUE THREAD

**Issue by AdrienHorgnies** [bastienmichaux/generator-jhipster-db-helper#11]
##### **Overview of the issue**

Our unit tests have a 0% coverage at the moment. We must work on that.

##### **Motivation for or Use Case**

Nobody would want something untested and it will ensure everything works as intended, even after modification, that's what tests are for.

##### **Suggest a Fix**

Do unit tests. We already have a start in the folder `test`.

---
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by AdrienHorgnies** [comment]
I'm closing this issue as of now because of #19 blocking the resolution of this. We have a test coverage of 100% for [db-constants.js][constants] and [dbh.js][dbh]

[constants]: https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/master/generators/dbh-constants.js
[dbh]: https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/master/generators/dbh.js

**Comment by bastienmichaux** [comment]
Once we have a polyfill we'll have a good test coverage.
