### ISSUE TITLE
Import database from connection or export

### ISSUE THREAD

**Issue by AdrienHorgnies** [bastienmichaux/generator-jhipster-db-helper#12]
##### **Overview of the issue**

Our module ease the generation of an application using an existing database but it's still could be much easier if we could just feed the database and wait it's ready. Be it with an export or a connection to the database.

##### **Motivation for or Use Case**

Save more time.

---
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by bastienmichaux** [comment]
We need to know the input type(s) : sql, json, xml ? Each type has its grammar, each grammar means a different parsing process, dependencies, tests, etc.

**Comment by AdrienHorgnies** [comment]
We'll most probably not handle the parsing process ourself but use an existing product. We'll see to that after the testing issues.

**Comment by bastienmichaux** [comment]
Ground work has begun in a separate module, in order to keep concerns separated with this module.

[Node-db-importer on Github](https://github.com/bastienmichaux/node-db-importer)

**Comment by AdrienHorgnies** [comment]
It's not an issue for this repository anymore then.
