### ISSUE TITLE
referenced tableName is incorrect

### ISSUE THREAD

**Issue by AdrienHorgnies** [bastienmichaux/generator-jhipster-db-helper#15]
##### **Overview of the issue**

When two entities have a relation, the owner of the relation doesn't reference the correct table in the event that the latter was renamed by our module.

```xml
        <addForeignKeyConstraint baseColumnNames="author_id"
                                 baseTableName="book"
                                 constraintName="fk_book_author_id"
                                 referencedColumnNames="id"
                                 referencedTableName="author"/>
```
The last field, `referencedTableName` is still entirely handled by Jhipster but we should intervene in the event that the module renamed that table.

##### **Motivation for or Use Case**

The generated database will be incorrect and won't be able to answer to REST requests on these tables.

##### **Reproduce the error**

1. Create two entities : 
   * Author
   * Book
1. Rename Author table name to Scribe using our module.
1. `mvn test` or `.mvnw`

##### **Related issues**

It is in the continuation of #3 .

##### **Suggest a Fix**

The problem with the generated `src/main/resources/config/liquibase/changelog/**_added_constraints_Book.xml`.
The entry `referencedTableName` is incorrect and should be changed to match the actual table name as our module renamed it.

##### **JHipster & JHipster-db-helper Version(s)**

4.3.0

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "book",
            "otherEntityName": "book",
            "relationshipType": "one-to-one",
            "ownerSide": false,
            "otherEntityRelationshipName": "author"
        }
    ],
    "fields": [],
    "changelogDate": "20170428083438",
    "dto": "no",
    "service": "no",
    "entityTableName": "author",
    "pagination": "no"
}
```
```json
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "author",
            "otherEntityName": "author",
            "relationshipType": "one-to-one",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "book"
        }
    ],
    "fields": [],
    "changelogDate": "20170428083501",
    "dto": "no",
    "service": "no",
    "entityTableName": "book",
    "pagination": "no"
}
```

---
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by AdrienHorgnies** [comment]
* `(relationshipType == 'many-to-one' || (relationshipType == 'one-to-one' && ownerSide))` : 
   * `referencedTableName="<%= otherEntityTableName %>"`.
* `(relationshipType == 'many-to-many' && ownerSide)` : 
   * `referencedTableName="<%= entityTableName %>"` as self reference
   * `referencedTableName="<%= otherEntityTableName %>"` as a reference the other table.

**Comment by AdrienHorgnies** [comment]
OK, we have two options here :
* The easy one - More than adding the entry `"dbhTableName"`, we set the value of `"entityTableName"`. This will ensure that when creating a relationship, the owner entity will receive the correct information. Furthermore, `"dbhTableName"` will pretty much be useless.
* The hard one - Read the configuration file of the entity referenced by `"otherEntityTableName"`, retrieve the correct value and **search and replace**.

I have a preference for the easy one, I can't really see any downside. For the hard one, we will maybe have to do something like that for the `referencedColumnNames`. Not quite sure thou.

**Comment by bastienmichaux** [comment]
The easier option should be preferred, but as we discussed, let's have a .dbh.json file so we can keep track of the user input and retrieve it at the writing phase. Should JHipster have replaced a property, making the application crash, we could use a simple try catch to update the entity file.

**Comment by AdrienHorgnies** [comment]
Ok, I'll do the easy option, ensure everything is working (there might still be a problem with Entity.OtherEntity_id field) then work on putting everything in this .dbh folder.
