### ISSUE TITLE
'RunContext.withGenerators()' ignores 'composeWith' with a local property

### ISSUE THREAD

**Issue by bastienmichaux** [bastienmichaux/generator-jhipster-db-helper#19]
##### **Overview of the issue**

We can't [run tests](https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/b4e525e7cb42d7ddb7328b6faae4c7fe914707bd/test/test-app.js#L20-L33) for some functions because `yeoman-test`'s `RunContext.withGenerators` ignores `composeWith()`. Because of this, when running `npm test`, the `jhipsterVar` object doesn't get the properties it should have.

This causes calls to functions like `_replaceNamingStrategies` to fail **when testing** (otherwise, the module works fine). Calls to `jhipsterFunc` methods fail too. In other words, lots of critical functionalities can't be tested.

The issue [is known](https://github.com/yeoman/generator/issues/704) by the Yeoman team.

##### **Motivation for or Use Case**

No test, no game.

##### **Reproduce the error**

Pull remote branch 'wtf' (*Why Tests Fail*) and run `npm test`. All tests pass but look at the log and you'll see a stack trace like this :

```
  Post app hook
TypeError: Cannot read property 'buildTool' of undefined
    at child.writing (/home/altissiadev/Desktop/jhimod/generator-jhipster-db-helper/generators/app/index.js:108:65)
    at Object.<anonymous> (/home/altissiadev/Desktop/jhimod/generator-jhipster-db-helper/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/altissiadev/Desktop/jhimod/generator-jhipster-db-helper/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /home/altissiadev/Desktop/jhimod/generator-jhipster-db-helper/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /home/altissiadev/Desktop/jhimod/generator-jhipster-db-helper/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
```

##### **Suggest a Fix**

Try implementing [`proxyquire`](https://github.com/thlorenz/proxyquire) as mentioned above in the [Yeoman issue](https://github.com/yeoman/generator/issues/704).

##### **JHipster & JHipster-db-helper Version(s)**

jhipster-db-helper v0.0.5.

---
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm this issue.
I can reproduce it with a simple module, generated with generator-jhipster-module

This hack doesn't work anymore :(
```javascript
            this.composeWith('jhipster:modules',
                { jhipsterVar, jhipsterFunc },
                this.options.testmode ? { local: require.resolve('generator-jhipster/generators/modules') } : null
            );
```

**Comment by AdrienHorgnies** [comment]
It seems we can't do anything at the moment. :sob: 
We'll skip this to focus on integration tests with Travis.

**Comment by bastienmichaux** [comment]
We'll use a polyfill as a temporary solution. I doubt I can contribute to the yeoman-test issue anytime soon and the use of proxyquire hasn't solved the problem.

**Comment by bastienmichaux** [comment]
From our experience working on this issue, there are 2 possible workarounds :

* directly replace missing jhipsterVar/jhipsterFunc properties, as we did using a [polyfil ](https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/44253d9ca25ac2e246df0591bea79471edcbd9d7/generators/app/index.js#L92-L127) (but it mixes test code with normal code, so it's not clean)
* use Travis, but it's a slower workflow than the one you can have with npm
