### ISSUE TITLE
Set cases for unit testing and continuous integration testing

### ISSUE THREAD

**Issue by bastienmichaux** [bastienmichaux/generator-jhipster-db-helper#22]
Now that we have a polyfill, we need to set some cases for our unit tests and our Travis builds. I'll begin with the unit tests since they must come first and they help us defining use cases.

Feel free to add test cases I didn't think about :

* **Post app hook** :
  * replace the naming strategies for an application using Maven as its build tool
  * replace the naming strategies for an application using Gradle as its build tool
* **Post entity hook** :
  * modify table, column and relationship names for [Jhipster's example Author-Book db](https://jhipster.github.io/creating-an-entity/#tutorial)
  * same for Oracle human resources sample db (a much more complex example db)

We need appropriate template files for the current JHipster version (4.4.x), we're still testing on 4.3.x.

For the post entity hook in our Travis build, let's do it first for MySQL, then gradually add support for other sql databases.

**Comment by AdrienHorgnies** [comment]
Coverage is not 100% but it's there.
