### ISSUE TITLE
Could not compose module using import-jdl

### ISSUE THREAD

**Issue by zsiddiqi** [bastienmichaux/generator-jhipster-db-helper#46]
This issue occurs on a freshly created project to which entities are added through the JDL import command.

##### **Overview of the issue**

Once the DbH sub-generator is run for the first time and configures itself within the project, running the import-jdl command does not automatically call the DbH post hook to ask the additional questions for each entity that is being imported

##### **Motivation for or Use Case**

If a project has DbH enabled and new Entities are imported via import-jdl command, DbH should run integrated for each of the new entities being imported.

##### **Reproduce the error**

$ cd my-jhipster-project-directory
$ yarn add generator-jhipster-db-helper
$ yo jhipster-db-helper
$ jhipster import-jdl JDL-schema.jh

You will get the following block for each one of your entities:

Running `webpack:build:dev` to update client app

Running post run module hooks

Could not compose module generator-jhipster-db-helper.
Make sure you have installed the module with 'npm -g generator

##### **Related issues**

None

##### **Suggest a Fix**

As a work around, the following command needs to be run manually for each of the entities:

$ yo jhipster:entity <ForEachEntity>

##### **JHipster & JHipster-db-helper Version(s)**

JHipster Version: 4.5.6, JHipster-db-helper Version: 0.1.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.app",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "exampleApp",
    "packageName": "com.example.app",
    "packageFolder": "com/example/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "c176a0e99714cc66d2f454a982b274d5ea7181dd",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "errorCode",
            "dbhColumnName": "error_code",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 40
        },
        {
            "fieldName": "description",
            "dbhColumnName": "description",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 250
        },
        {
            "fieldName": "created",
            "dbhColumnName": "created",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "lastModified",
            "dbhColumnName": "last_modified",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170706143236",
    "entityTableName": "app_error",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "serviceImpl",
    "angularJSSuffix": "",
    "dbhIdName": "id"
}

##### **Browsers and Operating System**

Mac OS Sierra Version: 10.12.5 (16F73)
Chrome: 61.0.3150.0 (Official Build) canary (64-bit)

---
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by AdrienHorgnies** [comment]
AH ok, I get it now, you were using the import-jdl.

It's not supported yet. The point of the JDL is to generate all your entities in one go but our module only works one entity at a time at the moment. I don't think we can do something good without some work from the JDL side. We've talk with its creator and that may happen. 

We're currently working on a database import so we're bound to do something about that but I can't give a date for now, we're still studying the possibilities. 

As for now, I'll look on how to suppress this error message and maybe ease the next steps.

**Comment by AdrienHorgnies** [comment]
After following the issue jhipster/generator-jhipster#6218, I've observed that this issue has been solved by a change in import-jdl. So, this bug is solved as of jhipster 4.6.2 but it may be a previous version that fixed it.
