### ISSUE TITLE
JsonProperty import failed

### ISSUE THREAD

**Issue by ludoo0d0a** [bastienmichaux/generator-jhipster-db-helper#54]
##### **Overview of the issue**
because io @JsonProperty  usage, we need to import the required class
but JsonProperty import failed if no cache

##### **Suggest a Fix**
Change placeholder from 
[import org.hibernate.annotations.Cache](https://github.com/bastienmichaux/generator-jhipster-db-helper/blob/95bd1d2c0773e0de89c9b05ac5867a4bee7d8666/generators/fix-entity/index.js#L234)
to 
import java.io.Serializable

##### **JHipster & JHipster-db-helper Version(s)**
jhipster 4.14.3
jhipster-db-helper 1.0.0

**Comment by AdrienHorgnies** [comment]
I currently have a problem with this annotation for the pull request #52 so I'll handle this in it.
