### ISSUE TITLE
Wrong default column name on relationship

### ISSUE THREAD

**Issue by GuiF007** [bastienmichaux/generator-jhipster-db-helper#57]
##### **Overview of the issue**
Not sure it can be considerated as bug, but it's surprising to have a default column name in plurial on relationship...

If an Author entity as a Nationality (So Many-to-One relationship), the default column name in the Author table is nationalities_id. jHipster default name is singular.

##### **Motivation for or Use Case**
Fit jHipster column names 

##### **Reproduce the error**
Just generate an entity with a relationship

##### **Suggest a Fix**
Singular name

##### **JHipster & JHipster-db-helper Version(s)**
jHipster 5.0.0-beta.1
jHipster-db-helper 1.1.0

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by AdrienHorgnies** [comment]
I must have messed up between many-to-many and other relationship. I will check that soon.

**Comment by AdrienHorgnies** [comment]
Well the purpose was to offer the same default values as JHipster so we don't modify the application when not needed.

**Comment by GuiF007** [comment]
Sure no problem !

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AdrienHorgnies** [comment]
Closing this issue as it was an intended feature. Several months later.
