### ISSUE TITLE
Can't run with JHipster v4.13.3

### ISSUE THREAD

**Issue by dapperdanman** [bastienmichaux/generator-jhipster-db-helper#60]
- Look closed and opened issues to check if it isn't already tracked.
- Please follow the issue template below for bug reports and feature requests.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**
I'm trying to use this with version 4.13.3 of JHipster and I get an error:

yarn global add generator-jhipster-db-helper
yarn global v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error generator-jhipster@5.5.0: The engine "node" is incompatible with this module. Expected version ">=8.10.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

##### **Motivation for or Use Case**

I haven't upgraded to the latest JHipster. This project obviously worked at one point with JHipster 4.13.3...

##### **Reproduce the error**

See above

##### **Related issues**

none

##### **JHipster & JHipster-db-helper Version(s)**

v4.13.3
v1.0

I tried forcing v0.1.1 to be installed, but when I run it, it doesn't ask me any questions. 

yo jhipster-db-helper
JHipster db-helper generator v0.1.1
Composing JHipster configuration with module db-helper
WARNING! DEPRECATED! The JHipster module sub-generator is deprecated.
WARNING! Please import the generator-base.js using commonJS require or ES2015 import.
WARNING! See http://www.jhipster.tech/modules/creating-a-module for more details.

Reading the JHipster project configuration for your module
identical src/main/resources/config/application.yml
identical src/test/resources/config/application.yml
identical pom.xml

I'm all done. Running yarn install for you to install the required dependencies. If this fails, try running the command yourself.

##### **JHipster configuration**

will provide if needed

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

will provide if needed

##### **Browsers and Operating System**

Linux RHEL 6

---
- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by AdrienHorgnies** [comment]
@dapperdanman Sorry I didn't come by sooner.

As other people have tested the module with the newest version of JHipster, I'm closing this issue. Either it has been "fixed" or there was a specific way to operate the module.

If you still have the problem, message this thread and I'll reopen.
